In [12]:
# Core libraries
import pandas as pd
import numpy as np
import json

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Statistical analysis
from scipy import stats
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# Project config
from src.params import *
from src.ingestion.openaq import OpenAQClient

# Plot configuration
%matplotlib inline
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

In [13]:
client = OpenAQClient(api_key= API_AQ, radius= 7000)

In [14]:
rio = client.fetch_location(lat= -22.9083, lon= -43.1764)

In [20]:
rio

{'meta': {'name': 'openaq-api',
  'website': '/',
  'page': 1,
  'limit': 1000,
  'found': 8},
 'results': [{'id': 820323,
   'name': 'Centro Kunak ',
   'locality': 'Rio de Janeiro',
   'timezone': 'America/Sao_Paulo',
   'country': {'id': 45, 'code': 'BR', 'name': 'Brazil'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 62, 'name': 'Rio City Hall'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 4475452,
     'name': 'co ppm',
     'parameter': {'id': 8,
      'name': 'co',
      'units': 'ppm',
      'displayName': 'CO'}},
    {'id': 4475460,
     'name': 'o3 µg/m³',
     'parameter': {'id': 3,
      'name': 'o3',
      'units': 'µg/m³',
      'displayName': 'O₃ mass'}},
    {'id': 6344694,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 14798912,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -22.9084, 'longitude': -43.1795},
   'licenses': None,
   'bounds': [-43.1795, -22.9084, -43.1795, -22.9084],
   'distance': 318.22677625,
   'datetimeFirst': {'utc': '2023-04-06T16:00:00Z',
    'local': '2023-04-06T13:00:00-03:00'},
   'datetimeLast': {'utc': '2026-02-16T08:00:00Z',
    'local': '2026-02-16T05:00:00-03:00'}},
  {'id': 5110474,
   'name': 'Presidente Vargas',
   'locality': 'Rio de Janeiro',
   'timezone': 'America/Sao_Paulo',
   'country': {'id': 45, 'code': 'BR', 'name': 'Brazil'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 62, 'name': 'Rio City Hall'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 13626664,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 13626662,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -22.9035, 'longitude': -43.1879},
   'licenses': None,
   'bounds': [-43.1879, -22.9035, -43.1879, -22.9035],
   'distance': 1294.04325291,
   'datetimeFirst': {'utc': '2025-07-17T18:00:00Z',
    'local': '2025-07-17T15:00:00-03:00'},
   'datetimeLast': {'utc': '2026-02-16T08:00:00Z',
    'local': '2026-02-16T05:00:00-03:00'}},
  {'id': 5110511,
   'name': 'Campo de Santana',
   'locality': 'Rio de Janeiro',
   'timezone': 'America/Sao_Paulo',
   'country': {'id': 45, 'code': 'BR', 'name': 'Brazil'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 62, 'name': 'Rio City Hall'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 13626934,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 13626932,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -22.9081, 'longitude': -43.1865},
   'licenses': None,
   'bounds': [-43.1865, -22.9081, -43.1865, -22.9081],
   'distance': 1036.41320266,
   'datetimeFirst': {'utc': '2025-07-17T18:00:00Z',
    'local': '2025-07-17T15:00:00-03:00'},
   'datetimeLast': {'utc': '2026-02-16T08:00:00Z',
    'local': '2026-02-16T05:00:00-03:00'}},
  {'id': 5636852,
   'name': 'MAM',
   'locality': 'Rio de Janeiro',
   'timezone': 'America/Sao_Paulo',
   'country': {'id': 45, 'code': 'BR', 'name': 'Brazil'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 62, 'name': 'Rio City Hall'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 14012772,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 14021533,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -22.913, 'longitude': -43.1702},
   'licenses': None,
   'bounds': [-43.1702, -22.913, -43.1702, -22.913],
   'distance': 821.87576906,
   'datetimeFirst': {'utc': '2025-09-01T15:00:00Z',
    'local': '2025-09-01T12:00:00-03:00'},
   'datetimeLast': {'utc': '2026-02-16T08:00:00Z',
    'local': '2026-02-16T05:00:00-03:00'}},
  {'id': 5636888,
   'name': 'Praça XV',
   'locality': 'Rio de Janeiro',
   'timezone': 'America/Sao_Paulo',
   'country': {'id': 45, 'code': 'BR', 'name': 'Brazil'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 62, 'name': 'Rio City Hall'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 14013034,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 14013033,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -22.9014, 'longitude': -43.173},
   'licenses': None,
   'bounds': [-43.173, -22.9014, -43.173, -22.9014],
   'distance': 839.97736308,
   'datetimeFirst': {'utc': '2025-09-01T16:00:00Z',
    'local': '2025-09-01T13:00:00-03:00'},
   'datetimeLast': {'utc': '2026-02-16T08:00:00Z',
    'local': '2026-02-16T05:00:00-03:00'}},
  {'id': 6152582,
   'name': 'Caju',
   'locality': 'Rio de Janeiro',
   'timezone': 'America/Sao_Paulo',
   'country': {'id': 45, 'code': 'BR', 'name': 'Brazil'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 62, 'name': 'Rio City Hall'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 14798938,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 14798940,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -22.8802, 'longitude': -43.2268},
   'licenses': None,
   'bounds': [-43.2268, -22.8802, -43.2268, -22.8802],
   'distance': 6035.27291774,
   'datetimeFirst': {'utc': '2025-12-04T20:00:00Z',
    'local': '2025-12-04T17:00:00-03:00'},
   'datetimeLast': {'utc': '2026-02-16T08:00:00Z',
    'local': '2026-02-16T05:00:00-03:00'}},
  {'id': 6152587,
   'name': 'Lagoa',
   'locality': 'Rio de Janeiro',
   'timezone': 'America/Sao_Paulo',
   'country': {'id': 45, 'code': 'BR', 'name': 'Brazil'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 62, 'name': 'Rio City Hall'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 14798915,
     'name': 'no2 µg/m³',
     'parameter': {'id': 5,
      'name': 'no2',
      'units': 'µg/m³',
      'displayName': 'NO₂ mass'}},
    {'id': 14798928,
     'name': 'o3 µg/m³',
     'parameter': {'id': 3,
      'name': 'o3',
      'units': 'µg/m³',
      'displayName': 'O₃ mass'}},
    {'id': 14798907,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 14798916,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -22.9614, 'longitude': -43.2035},
   'licenses': None,
   'bounds': [-43.2035, -22.9614, -43.2035, -22.9614],
   'distance': 6504.34330018,
   'datetimeFirst': {'utc': '2025-12-04T20:00:00Z',
    'local': '2025-12-04T17:00:00-03:00'},
   'datetimeLast': {'utc': '2026-02-16T08:00:00Z',
    'local': '2026-02-16T05:00:00-03:00'}},
  {'id': 6178275,
   'name': 'Tijuca Aurassure',
   'locality': 'Rio de Janeiro',
   'timezone': 'America/Sao_Paulo',
   'country': {'id': 45, 'code': 'BR', 'name': 'Brazil'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 62, 'name': 'Rio City Hall'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 14990321,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 14990322,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -22.9244, 'longitude': -43.2322},
   'licenses': None,
   'bounds': [-43.2322, -22.9244, -43.2322, -22.9244],
   'distance': 5995.52222912,
   'datetimeFirst': {'utc': '2025-12-26T05:00:00Z',
    'local': '2025-12-26T02:00:00-03:00'},
   'datetimeLast': {'utc': '2026-02-16T08:00:00Z',
    'local': '2026-02-16T05:00:00-03:00'}}]}

In [18]:
rio_sensors = client.filter_sensors(rio, start_project_date= START_PROJECT_DATE_STR, end_project_date= END_PROJECT_DATE_STR)
rio_sensors

==================================================
Initial monitor-grade sensors: 8
Sensors active at end date: 8
Sensors with full coverage: 1
==================================================

[14798912]

In [19]:
rio_data = client.fetch_one_sensor_data(sensor_id=14798912, start_date= START_TRAIN_DATE_STR, end_date= END_TRAIN_DATE_STR, cache_dir="../data/cache/Rio de Janeiro")

In [3]:
df_aq = pd.read_csv("../data/raw/aq_data.csv")

In [11]:
df_aq["city"].unique()

array(['Paris', 'Lyon', 'New York', 'Los Angeles', 'Delhi', 'London',
       'Berlin', 'Rome', 'Barcelona', 'Mumbai', 'Mexico City', 'Santiago'],
      dtype=object)

# Base EDA

## Stats on sensors availability

In [ ]:
sensors_stats = pd.DataFrame(df_aq.groupby("city")["sensor_id"].nunique())

             sensor_id
city
Barcelona            1
Berlin               3
Delhi               10
London              14
Los Angeles          1
Lyon                 3
Mexico City          3
Mumbai               5
New York             6
Paris                3
Rome                 6
Santiago             2

In [ ]:
# cities and sensors and average daily coverage
stats_sensors = pd.DataFrame({"cities": df_aq["city"].unique(),
 "nb_sensors": df_aq.groupby("city")["sensor_id"].nunique()
 })

                  cities  nb_sensors
city
Barcelona          Paris           1
Berlin              Lyon           3
Delhi           New York          10
London       Los Angeles          14
Los Angeles        Delhi           1
Lyon              London           3
Mexico City       Berlin           3
Mumbai              Rome           5
New York       Barcelona           6
Paris             Mumbai           3
Rome         Mexico City           6
Santiago        Santiago           2